server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: casual-rent
  profiles:
    active: pro
  
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB

# JSON配置
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/*.xml

# 日志配置
logging:
  level:
    com.casual.rent: debug
    org.springframework.security: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'

# 自定义配置
app:
  # 腾讯云OSS配置
  tencent:
    cos:
      secret-id: ${TENCENT_SECRET_ID}
      secret-key: ${TENCENT_SECRET_KEY}
      region: ${TENCENT_COS_REGION}
      bucket-name: ${TENCENT_COS_BUCKET}
      domain: ${TENCENT_COS_DOMAIN}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
